version: '3.9'
services:
  products:
    container_name: products
    build: ./backend/products
    ports:
      - 4001:4001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      products_db:
        condition: service_healthy
    environment:
      - APP_PORT=4001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=products_db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4001"]
      timeout: 10s
      retries: 5
  products_db:
    image: mysql:8.0.21
    container_name: products_db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores